version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "443:9000"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: sample_app
      DB_USERNAME: SAAS
      DB_PASSWORD: Password1
    entrypoint: ["/var/www/html/entrypoint.sh"]

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: sample_app
      MYSQL_USER: SAAS
      MYSQL_PASSWORD: Password1
      MYSQL_ROOT_PASSWORD: Password1
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: