# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - lyo14

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: https://dockerapptclo.azurecr.io
          username: dockerapptclo
          password: YIor6RLdJT7b5/B0VOAQ07sTdXEMw+NAlhycO4Iprq+ACRARu6Im

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          configuration-file: docker-compose.yml
          push: true
          tags: dockerapptclo.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_08fcb00f523e4f9b922413b567826b6c }}/docker-app:${{ github.sha }}
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'lyo14'
          configuration-file: docker-compose.yml
          slot-name: 'production'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_625c11ab67e14a8ca78e9e237724deab }}
          images: 'dockerapptclo.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_08fcb00f523e4f9b922413b567826b6c }}/docker-app:${{ github.sha }}'
